include: package:pedantic/analysis_options.1.11.0.yaml
 
linter:
  rules:
    # Nice rules unused by pedantic 1.9.0
    - always_put_control_body_on_new_line
    - avoid_function_literals_in_foreach_calls
    - avoid_renaming_method_parameters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - no_adjacent_strings_in_list
    - non_constant_identifier_names
    - package_names
    - package_prefixed_library_names
    - prefer_asserts_in_initializer_lists
    - prefer_const_declarations
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    - prefer_relative_imports
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_brace_in_string_interps
    - unnecessary_null_aware_assignments
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - unawaited_futures
    - use_full_hex_values_for_flutter_colors
    - avoid_returning_this
    - avoid_types_on_closure_parameters
    - avoid_unnecessary_containers
    - file_names
    - no_runtimeType_toString
    - only_throw_errors
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_constructors_over_static_methods
    - prefer_function_declarations_over_variables
    - prefer_interpolation_to_compose_strings
    - prefer_is_not_operator
    - prefer_null_aware_operators
    - unnecessary_lambdas
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - use_string_buffers
